#!/bin/bash -eu

script_dir=$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)

function usage() {
    echo "$0 [home_dir]"
    echo "Example: $0 $HOME"
    exit 1
}

if [ $# -lt 1 ]; then
    usage
fi

home_dir=$1

function link_it() {
    local source=$1
    local target=$2

    echo "Linking $source to $target"
    if [[ -d $target && ! -h $target ]]; then
        echo "ERROR: $target is a real directory, failing to link - remove it first"
    else
        ln -snf $source $target
    fi
}

function link_file() {
    local file=$1
    local base=$(basename $file)

    if [[ $base == *.bin ]]; then
        mkdir -p $home_dir/bin
        local target="$home_dir/bin/${base:0:-4}"
        link_it $file $target
    elif [ -d $file ]; then
        mkdir -p $home_dir/.$base
        for subfile in $file/*; do
            local target="$home_dir/.$base/$(basename $subfile)"
            link_it $subfile $target
        done
    elif [ -f $file ]; then
        local target="$home_dir/.$base"
        link_it $file $target
    fi
}

function link_files() {
    local dir=$1

    for file in $dir/*; do
        link_file $file
    done
}

function main() {
    for dir in $script_dir/*; do
        if [ -d $dir ]; then
            link_files $dir
        fi
    done
}

main
